const maskImages = [
  { id: 1, src: "/img/mask/1.jpg", alt: "noi" },
  { id: 2, src: "/img/mask/2.jpg", alt: "noi" },
  { id: 3, src: "/img/mask/3.jpg", alt: "noi" },
  { id: 4, src: "/img/mask/4.jpg", alt: "noi" },
  { id: 5, src: "/img/mask/5.jpg", alt: "noi" },
  { id: 6, src: "/img/mask/6.jpg", alt: "noi" },
  { id: 7, src: "/img/mask/7.jpg", alt: "noi" },
  { id: 8, src: "/img/mask/8.jpg", alt: "noi" },
  { id: 9, src: "/img/mask/9.jpg", alt: "noi" },
  { id: 10, src: "/img/mask/10.jpg", alt: "noi" },
  { id: 11, src: "/img/mask/11.jpg", alt: "noi" },
  { id: 12, src: "/img/mask/12.jpg", alt: "noi" },
  { id: 13, src: "/img/mask/13.jpg", alt: "noi" },
  { id: 14, src: "/img/mask/14.jpg", alt: "noi" },
  { id: 15, src: "/img/mask/15.jpg", alt: "noi" },
  { id: 16, src: "/img/mask/16.jpg", alt: "noi" },
  { id: 17, src: "/img/mask/17.jpg", alt: "noi" },
  { id: 18, src: "/img/mask/18.jpg", alt: "noi" },
  { id: 19, src: "/img/mask/19.jpg", alt: "noi" },
  { id: 20, src: "/img/mask/20.jpg", alt: "noi" },
  { id: 21, src: "/img/mask/21.jpg", alt: "noi" },
  { id: 22, src: "/img/mask/22.jpg", alt: "noi" },
  { id: 23, src: "/img/mask/23.jpg", alt: "noi" },
  { id: 24, src: "/img/mask/24.jpg", alt: "noi" },
  { id: 25, src: "/img/mask/25.jpg", alt: "noi" },
];

export default maskImages;
