const noMaskImages = [
  { id: 1, src: "/img/no_mask/1.jpg", alt: "noi" },
  { id: 2, src: "/img/no_mask/2.jpg", alt: "noi" },
  { id: 3, src: "/img/no_mask/3.jpg", alt: "noi" },
  { id: 4, src: "/img/no_mask/4.jpg", alt: "noi" },
  { id: 5, src: "/img/no_mask/5.jpg", alt: "noi" },
  { id: 6, src: "/img/no_mask/6.jpg", alt: "noi" },
  { id: 7, src: "/img/no_mask/7.jpg", alt: "noi" },
  { id: 8, src: "/img/no_mask/8.jpg", alt: "noi" },
  { id: 9, src: "/img/no_mask/9.jpg", alt: "noi" },
  { id: 10, src: "/img/no_mask/10.jpg", alt: "noi" },
  { id: 11, src: "/img/no_mask/11.jpg", alt: "noi" },
  { id: 12, src: "/img/no_mask/12.jpg", alt: "noi" },
  { id: 13, src: "/img/no_mask/13.jpg", alt: "noi" },
  { id: 14, src: "/img/no_mask/14.jpg", alt: "noi" },
  { id: 15, src: "/img/no_mask/15.jpg", alt: "noi" },
  { id: 16, src: "/img/no_mask/16.jpg", alt: "noi" },
  { id: 17, src: "/img/no_mask/17.jpg", alt: "noi" },
  { id: 18, src: "/img/no_mask/18.jpg", alt: "noi" },
  { id: 19, src: "/img/no_mask/19.jpg", alt: "noi" },
  { id: 20, src: "/img/no_mask/20.jpg", alt: "noi" },
  { id: 21, src: "/img/no_mask/21.jpg", alt: "noi" },
  { id: 22, src: "/img/no_mask/22.jpg", alt: "noi" },
  { id: 23, src: "/img/no_mask/23.jpg", alt: "noi" },
  { id: 24, src: "/img/no_mask/24.jpg", alt: "noi" },
  { id: 25, src: "/img/no_mask/25.jpg", alt: "noi" },
  { id: 26, src: "/img/no_mask/26.jpg", alt: "noi" },
  { id: 27, src: "/img/no_mask/27.jpg", alt: "noi" },
  { id: 28, src: "/img/no_mask/28.jpg", alt: "noi" },
  { id: 29, src: "/img/no_mask/29.jpg", alt: "noi" },
  { id: 30, src: "/img/no_mask/30.jpg", alt: "noi" },
  { id: 31, src: "/img/no_mask/31.jpg", alt: "noi" },
  { id: 32, src: "/img/no_mask/32.jpg", alt: "noi" },
  { id: 33, src: "/img/no_mask/33.jpg", alt: "noi" },
  { id: 34, src: "/img/no_mask/34.jpg", alt: "noi" },
  { id: 35, src: "/img/no_mask/35.jpg", alt: "noi" },
];

export default noMaskImages;
